import Head from "next/head";
import React from "react";
import Logo from "@/assets/logo-rda.png";

const HeadMeta = ({
  title = "Portfolio",
  metaDescription,
  ogImageUrl = Logo,
  pathname = "",
}) => {
  const defaultTitle = "Hello, I am Rizky Dipahiyat Alghipari";

  const baseUrl =
    process.env.NEXT_NODE_ENV === "development"
      ? "http://localhost:3000"
      : "https://hirizky.netlify.app";

  const pageUrl = new URL(pathname, baseUrl).toString();

  return (
    <Head>
      <title>{title + " | " + defaultTitle}</title>
      <meta name="description" content="Generated by create next app" />

      {/* Meta Data */}
      <meta name="title" content={title + " | " + defaultTitle} />
      <meta name="description" content={metaDescription} />
      <meta name="og:image" itemProp="image" content={ogImageUrl} />
      <meta property="og:url" content={pageUrl} />

      {/* Facebook Meta Tags */}
      <meta property="og:type" content="website" />
      <meta property="og:image" itemProp="image" content={ogImageUrl} />
      <meta property="og:title" content={title + " | " + defaultTitle} />
      <meta property="og:description" content={metaDescription} />

      {/* Twitter Meta Tags */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta property="twitter:url" content={pageUrl} />
      <meta name="twitter:title" content={title + " | " + defaultTitle} />
      <meta name="twitter:image" content={ogImageUrl} />
      <meta property="twitter:description" content={metaDescription} />
    </Head>
  );
};

export default HeadMeta;
